### ISSUE TITLE
MP3 Support on NW.js

### ISSUE THREAD

**Issue by makkii-bcr** [hoge1e3/Tonyu2#47]
NW.jsはmp3再生を既にサポートしていた！
が、Tonyu2DL版では現在mp3を鳴らせない。

Tonyu2ではPC内プロジェクト実行時、mp3ファイルの再生処理は同名のoggファイルを再生しようとする。
NW.js自体はmp3を再生できるが、Tonyu2がoggを再生しようとするため、mp3ファイルがあっても同名のoggが無い場合は鳴らない。

NW.jsがmp3非対応だった時代のロジックが原因で、Tonyu2DL版ではmp3が鳴らせない。
mp3を鳴らせるようにするには、mp3は直接再生するように処理の変更が必要。

**Comment by hoge1e3** [comment]
もともと，nw.js はmp3のライブラリ(ffmpeg)がGPLで（GPLのライブラリを使うと本体もGPLにしないといけないため）外してあった（ffmpeg.dll からGPL由来のものを取り外してあった）という経緯があります．
参考記事：https://akabeko.me/blog/2015/03/nw-5-audio-player/
現在もnw.js自身はMITライセンスのようですが，ffmpeg.dll がいつのまにかGPL由来になっている可能性があります．（ということはffmpeg.dll自身を同梱できない？？）

**Comment by hoge1e3** [comment]
続報です．credit.html を見ると，ほとんどのCodecは”L"GPL(劣等GPL:dllを使うだけならGPLにしなくていい）だとあり，特別なオプションをつけないとGPLのものは含まれないとあります．ただ，nw.jsサイトからダウンロードできるffmpeg.dll がGPL抜きになっているかどうかがまだ確認できていません．

**Comment by hoge1e3** [comment]
https://nwjs.io/blog/v0.22.1/
によると，mp3の特許が切れたためver22から入ったようです．nw.js本体はMITなのでおそらく大丈夫かなとは思います．

**Comment by makkii-bcr** [comment]
ありがとうございます。こちらでも調査していましたが同感です。

**Comment by hoge1e3** [comment]
対応しました．ご確認ください．

**Comment by makkii-bcr** [comment]
mp3が鳴らせるようになりました。ありがとうございます！

**Comment by makkii-bcr** [comment]
新バージョンをリリース後、以下のmp3の記述をmp4に変える必要あり。

https://www.tonyu.jp/tonyu2/ffmpeg.html

https://www.tonyu.jp/Tonyu2DL.php
音楽ファイルフォーマットについて

**Comment by makkii-bcr** [comment]
以下もmp3が再生できないことの記載を修正する必要あり
https://edit.tonyu.jp/doc/sndres.html

**Comment by hoge1e3** [comment]
こちらも0618で修正予定です．確認次第Closeしたいと思います．
